---
title: "Perimeter Method"
type: "exercise"
description: "Utilize arguments and return values to represent a geometric forumula"
tags: "methods, return-values, parameters, arguments"
visibility: "public"
ignore:
- "perimeter_method.md"
